### ISSUE TITLE
Issue Dedupe

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/generate-vector-embeddings#6]
On `issue.created` and `issue.edited` we should check if there are any open issues that are x% similar within the repository. There should be two configurable percentages: 
1. A `warning` threshold, perhaps 75% similar as a default 
2. "Match" threshold, 95% similar default. 

- If a "match" is found, the bot should "close as unplanned" 
- If a "warning" level issue has been found, post a comment with all the similar open issues. Target and edit this comment if it currently exists. 

It isn't entirely clear to me if this should be a separate plug-in, but this does require coupling to the same vector embeddings database. Another idea is to pass in the authentication details in each vector embeddings related plugin's config.

**Comment by 0x4007** [comment]
@sshivaditya2019 rfc

**Comment by sshivaditya2019** [comment]
This could be managed with a separate plugin if necessary. If `issue_content_embeddings` is enabled, we can use similarity search; otherwise, we can use other libraries like spaCy. The decision on how to design this depends on whether we are comfortable with increasing coupling between the two plugins or components.

**Comment by sshivaditya2019** [comment]
\start

**Comment by 0x4007** [comment]
Reducing coupling is preferred just as long as it doesn't make the setup overly complicated.

**Comment by sshivaditya2019** [comment]
Is it possible to retrieve the currently active plugins from within a plugin?

**Comment by 0x4007** [comment]
> Is it possible to retrieve the currently active plugins from within a plugin?

@gentlementlegen @Keyrxng RFC

I'm assuming by parsing the current config. I'm pretty sure we have a method in our SDK for this @whilefoo do you know?

**Comment by Keyrxng** [comment]
> Is it possible to retrieve the currently active plugins from within a plugin?

Yeah by parsing the private config file but I'm not sure why you'd need that to dedupe issues, all plugins right now are independent of each other if that was the concern.

I also don't understand why decoupling is a best practice for plugins, why enable plugin chaining if we should avoid it. But some plugins are going to be "coupled" and we can't help that, i.e any embeddings related feature.

---

> If issue_content_embeddings is enabled

`issue_comment_embeddings` is a core plugin I think (we are covering the OpenAI bill right?) which means it'll always be active. If it's not a core plugin and/or we are not covering the bill then the partner needs to be able to define their own storage, if this happens then you'd need to parse the config file for the `supabase_key` used in the embeddings plugin (no guarantee that the env vars are the same across partner plugins although they'd need to have a centralized embeddings storage for us to use)

All plugins which rely on org-wide embeddings are going to need a centralized storage space per partner or we need to improve our DB handling. Otherwise any AI feature dependent on these are going to need work arounds

---

Using the current embeddings doesn't really fit unless there is a specific embedding just for the issue body (not tied to a comment) and if those are specifically indexable then similarity search across those embeddings should do the trick yeah.

**Comment by 0x4007** [comment]
You should check the original conversation and pull instead of speculating on how it's implemented. 

As I understand, each vector embedding has an ID (issue id, comment id) 

GraphQL query of contributors closed as complete issues return IDs

We just check those IDs.

**Comment by Keyrxng** [comment]
> You should check the original conversation
> similar within the repository.

My mistake I misread this as within the org and I didn't think there would be any reliance on graphql or rest. I thought we'd cover all issues not just closed as complete and the embeddings would have relevant metadata to help filtering. When working with embeddings previously such as chunking pdfs etc they'd have relevant metadata for each chunk and I was considering each of ours as one chunk.

I guess centralizing the embedding db was also sort of mentioned too so yeah my bad I'll hide the comment and go get another coffee 😂

**Comment by whilefoo** [comment]
> > Is it possible to retrieve the currently active plugins from within a plugin?
> 
> @gentlementlegen @Keyrxng RFC
> 
> I'm assuming by parsing the current config. I'm pretty sure we have a method in our SDK for this @whilefoo do you know?

No we don't have that method.

Since both plugins would share the same database, maybe it would be better to keep it as one plugin?

**Comment by sshivaditya2019** [comment]
@0x4007 
I think it would be better to make this as an extension of `issue-comment-embeddings`, like something that can be enabled if required. 

To get the facts straight:

- This would be a part of `issue-comment-embeddings` plugin.
- If a `Match` threshold is found, it should close the issue automatically with `close as unplanned`.
- If a `Warning` threshold is found, it would display the similar issues found using the vector.

Please let me know if there are any errors or if further adjustments are needed.

**Comment by 0x4007** [comment]
All correct

**Comment by Keyrxng** [comment]
Should this plugin just be rebranded to `embeddings-plugin` and we can just keep all embedding-related features nice and compact? as all related features require the same vector db or will require multiple vector DBs depending on how other embedding types are stored.

A rebranding makes sense because `issue_comment_embeddings` suggests it's only creating them whereas `embeddings-plugin` sounds like it has many usecases.

Features such as `issueDepude` and others could be enabled/disabled per the plugin settings according to what a partner wants from their embeddings.

**Comment by 0x4007** [comment]
It's done

**Comment by sshivaditya2019** [comment]
I think this blocked by #8, once we are able to nail down a schema, this should be good to go.

**Comment by 0x4007** [comment]
I decided on a schema there

**Comment by sshivaditya2019** [comment]
> @sshivaditya2019, this task has been idle for a while. Please provide an update.

Combining in  PR #9

**Comment by sshivaditya2019** [comment]
@0x4007 Does the `ubiquibot-kernel`, support `issue.created`, `issue.edited` and `issue.deleted`, event emitter types ?. I am getting `TransformDecodeCheckError: Unable to decode value as it does not match the expected schema` for that.

**Comment by 0x4007** [comment]
> > @sshivaditya2019, this task has been idle for a while. Please provide an update.
> 
> 
> 
> Combining in  PR #9 

Pulls need to be separated. 

> @0x4007 Does the `ubiquibot-kernel`, support `issue.created`, `issue.edited` and `issue.deleted`, event emitter types ?. I am getting `TransformDecodeCheckError: Unable to decode value as it does not match the expected schema` for that.
> 
> 
> 
> I think this is a issue, with `ubiquibot-kernel`, as requests are not being passed to the worker.

Try issues plural instead. Check the type definitions.

**Comment by 0x4007** [comment]
@ubiquibot/software-development can somebody install this
